name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check code style (flake8)
        run: |
          source venv/bin/activate
          export PYTHONPATH=$PYTHONPATH:.
          # Ignoramos E302, E501, W391
          flake8 --ignore=E302,E501,W391 descargahtml_mitula generarcsv_mitula test

      - name: Run pytest (unit tests)
        run: |
          source venv/bin/activate
          export PYTHONPATH=$PYTHONPATH:.
          pytest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          # si usas session token:
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Deploy Lambda (descarga)
        run: |
          source venv/bin/activate
          cd descargahtml_mitula
          zappa update dev

      - name: Deploy Lambda (genera CSV)
        run: |
          source venv/bin/activate
          cd ../generarcsv_mitula
          zappa update dev
