name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: verificacion de perfil AWS
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}"
          echo "region=us-east-1"
          
      - name: Configuracion de las credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: us-east-1
      

      - name: Revision de codigo (flake8)
        run: |
          source venv/bin/activate
          export PYTHONPATH=$PYTHONPATH:.
          flake8 --ignore=E501,E302,W391 descargahtml_mitula generarcsv_mitula test

      - name: Pytest (pruebas unitarias a la descarga de html)
        run: |
          source venv/bin/activate
          export PYTHONPATH=$PYTHONPATH:.
          pytest

